CREATE TABLE ItemTypes
(ItemTypeID INT PRIMARY KEY,
[Name] VARCHAR (50) NOT NULL
)

CREATE TABLE Items
(
ItemID INT PRIMARY KEY,
[Name] VARCHAR (50) NOT NULL,
ItemTypeID INT REFERENCES ItemTypes(ItemTypeID)
)

CREATE TABLE Cities
(
CityID INT PRIMARY KEY,
[Name] VARCHAR(50) NOT NULL
)

CREATE TABLE Customers
(
CustomerID INT PRIMARY KEY,
[Name] VARCHAR(50) NOT NULL,
Birthday DATETIME ,
CityID INT REFERENCES Cities (CityID)
)
CREATE TABLE Orders
(
OrderID INT PRIMARY KEY,
CustomerID INT REFERENCES Customers(CustomerID)
)
CREATE TABLE OrderItems
(
OrderID INT,
ItemID INT

CONSTRAINT PK_Order_Item PRIMARY KEY (OrderID,ItemID),
CONSTRAINT FK_Order FOREIGN KEY (OrderID) REFERENCES Orders(OrderID),
CONSTRAINT FK_Item FOREIGN KEY (ItemID) REFERENCES Items(ItemID)

)